```{r eval=FALSE, include=FALSE}
#The following code imports code from an R markdown file by converting it to a .R file then using the source function to bring it over 

#The quiet argument, when set to TRUE, supresses messages and warnings generated by knitr::purl during the extraction process.
#By setting quiet=TRUE, the function will only return the source code, without any additional messages or warnings. This can be useful for making the code extraction process less verbose, or for suppressing messages that might interfere with your workflow.

source(knitr::purl("C:/Users/Ryan/Coding Projects/KDL Project/Wrangling.Rmd", quiet=TRUE)) 
```

```{r}
#taking in all the libraries and data wrangling from this initial R file 
source("C:/Users/Ryan/Coding Projects/KDL Project/Study Rooms/Wrangling.R") 
```


#Table containing general summary statistics about the data we collected.
```{r echo=FALSE}
#Function from the stringr library that will count all instances of 'yes' and 'no' observations from the variable Room_Avaliable 
y <-str_count(study$Room_Avaliable, "yes")
n <-str_count(study$Room_Avaliable, "no")

#Using the summarize function to create a data frame that highlights some important summary statistics to be included in the report  
m <-study %>%
  summarise(yes = sum(y), no = sum(n), total = yes+no, Success_Rate = yes/total,
            min = min(Numer_Of_People),
            max = max(Numer_Of_People),
            MeanG = mean(Numer_Of_People),
            MeanC = (total/18),
            sd = sd(Numer_Of_People),
            Median = median(Numer_Of_People)) 
print(m)

summary(study$Numer_Of_People)
```


#Cross tabulation illustrating the success rate of patrons getting a study room by the time of day
```{r echo=FALSE}
#this code is creating a cross-tabulation table from the study1 data frame and adding row and column totals, as well as a new column with the success rate calculated from the yes and Total columns. The success rate column is also formatted as a percentage.

tab <- tabyl(study1, Time, Room_Avaliable) %>%
  adorn_totals(c("row", "col")) %>%
  mutate(Success_rate = yes/Total) %>%
  adorn_pct_formatting(,,,Success_rate)

print(tab)
```



#Cross tabulation investigating success rate of getting a study by individual day 
```{r echo=FALSE}
# The as.Date() function is used to convert the orginal character date column into a date vector. It takes a character vector as input and returns a date vector with the same length. 
study$newdate <- as.Date(study$Date)

#Formats new date function into the format 11/07/2022 (month, day, 4 digit year)
study$newdate <- format(study$newdate, "%m/%d/%Y")

#Code to create a cross tabulation investigating success rate of getting a study by individual day applying the percent format to the success_rate column 
tab <- tabyl(study, newdate, Room_Avaliable) %>%
  adorn_totals(c("row", "col")) %>%
  mutate(Success_rate = yes/Total) %>%
  adorn_pct_formatting(,,,Success_rate) 
 
print(tab)
```

```{r}
#Code to export table to an excel sheet!

#write_xlsx(tab, "C:/Users/ryan/projects/kdl project/figs/Hi.xlsx")
```